In [ ]:
# !pip install requests
# !pip install beautifulsoup4
# !pip install sqlite3
# !pip install pandas

In [3]:
import requests
from bs4 import BeautifulSoup
import sqlite3
import pandas as pd

# Parte 1: Configuração e Criação do Banco de Dados

---

Criação
do banco de dados e conexão: Crie um novo banco de dados SQLite
chamado empresa.db.
Conecte-se a ele e verifique se a conexão foi bem concluída.

In [4]:
conexao = sqlite3.connect("empresa.db")
cursor = conexao.cursor()

Criação
de tabela

In [ ]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS funcionarios(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cargo text not null,
    salario real,
    data_contratacao texto not null)
""")

conexao.commit()

In [20]:
cursor.execute("PRAGMA table_info(funcionarios);")
cursor.fetchall()

[(0, 'id', 'INTEGER', 0, None, 1),
 (1, 'nome', 'TEXT', 1, None, 0),
 (2, 'cargo', 'TEXT', 1, None, 0),
 (3, 'salario', 'REAL', 0, None, 0),
 (4, 'data_contratacao', 'texto', 1, None, 0)]

# Parte 2: Manipulação de Dados (DML)

---

### Inserção de dados (INSERT):
 Insira pelo menos 5 registros na tabela funcionários com
dados fictícios.

In [11]:
cursor.executemany("insert into funcionarios VALUES (?, ?, ?, ?, ?)", [
    (1,"Felipe", "Analista de Dados", 5000.00, "2022-01-15"),
    (2, "Alice", "Arquiteta", 7000.00, "2021-09-10"),
    (3, "Acsa", "Engenheira de Software", 6000.00, "2023-03-20"),
    (4, "Aline", "Cientista de Dados", 8000.00, "2022-11-05")
])

conexao.commit()

### Consulta
de dados (SELECT): Escreva um comando SELECT para exibir todos os registros da tabela funcionários.

In [13]:
cursor.execute("select * from funcionarios;")
pd.DataFrame(cursor.fetchall(), columns=["id", "nome", "cargo", "salario", "data_contratacao"])

   id    nome                   cargo  salario data_contratacao
0   1  Felipe       Analista de Dados   5000.0       2022-01-15
1   2   Alice               Arquiteta   7000.0       2021-09-10
2   3    Acsa  Engenheira de Software   6000.0       2023-03-20
3   4   Aline      Cientista de Dados   8000.0       2022-11-05

### Filtro - WHERE:

- Selecione apenas os funcionários com salário superior a R$ 5000.
- Selecione os funcionários que trabalham como 'Gerente'.

In [18]:
cursor.execute("select * from funcionarios where salario > 5000;")
pd.DataFrame(cursor.fetchall(),columns=['id', 'nome', 'cargo', 'salario', 'data_contratacao'])

   id   nome                   cargo  salario data_contratacao
0   2  Alice               Arquiteta   7000.0       2021-09-10
1   3   Acsa  Engenheira de Software   6000.0       2023-03-20
2   4  Aline      Cientista de Dados   8000.0       2022-11-05

In [19]:
cursor.execute("select * from funcionarios where cargo = 'Analista de Dados';")
pd.DataFrame(cursor.fetchall(), columns=['id', 'nome', 'cargo', 'salario', 'data_contratacao'])

   id    nome              cargo  salario data_contratacao
0   1  Felipe  Analista de Dados   5000.0       2022-01-15

### Atualização de dados (UPDATE):

In [22]:
cursor.execute("update funcionarios set salario = salario * 1.1 where nome = 'Alice';")
conexao.commit()

### Exclusão de dados (DELETE):
 Exclui um dos funcionários que você inseriu.

In [23]:
cursor.execute("delete from funcionarios where nome = 'Felipe';")
conexao.commit()

### Contagem de registros:
 Conte o número total de funcionários na tabela.

In [ ]:
cursor.execute("select count(*) from funcionarios;")
cursor.fetchall()

[(3,)]

# Parte 3: Agregação e Ordenação

---

### Funções de agregação ( SUM, AVG, MAX, MIN):
- Calcule a soma total dos salários.
- Calcule o salário médio da empresa.
- Encontre o salário mais alto e o mais baixo.