In [2]:
# !pip install requests
# !pip install beautifulsoup4
# !pip install sqlite3
# !pip install pandas

In [3]:
import requests
from bs4 import BeautifulSoup
import sqlite3
import pandas as pd

# Parte 1: Configuração e Criação do Banco de Dados

---

Criação
do banco de dados e conexão: Crie um novo banco de dados SQLite
chamado empresa.db.
Conecte-se a ele e verifique se a conexão foi bem concluída.

In [10]:
conexao = sqlite3.connect("empresa.db")
cursor = conexao.cursor()

Criação
de tabela

In [11]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS funcionarios(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cargo text not null,
    salario real,
    data_contratacao texto not null)
""")

conexao.commit()

In [12]:
cursor.execute("PRAGMA table_info(funcionarios);")
cursor.fetchall()

[(0, 'id', 'INTEGER', 0, None, 1),
 (1, 'nome', 'TEXT', 1, None, 0),
 (2, 'cargo', 'TEXT', 1, None, 0),
 (3, 'salario', 'REAL', 0, None, 0),
 (4, 'data_contratacao', 'texto', 1, None, 0)]

# Parte 2: Manipulação de Dados (DML)

---

### Inserção de dados (INSERT):
 Insira pelo menos 5 registros na tabela funcionários com
dados fictícios.

In [14]:
# Se você executou esta célula antes, o erro acontece porque a coluna "id" é PRIMARY KEY
# e os valores 1,2,3,4 já existem. Como a tabela usa AUTOINCREMENT, basta não inserir
# os IDs manualmente e deixar o SQLite gerar os valores.

cursor.executemany(
    "INSERT INTO funcionarios (nome, cargo, salario, data_contratacao) VALUES (?, ?, ?, ?)",
    [
        ("Felipe", "Analista de Dados", 5000.00, "2022-01-15"),
        ("Alice", "Arquiteta", 7000.00, "2021-09-10"),
        ("Acsa", "Engenheira de Software", 6000.00, "2023-03-20"),
        ("Aline", "Cientista de Dados", 8000.00, "2022-11-05"),
        ("Bruno", "Gerente", 9500.00, "2020-05-18"),
    ]
)

conexao.commit()

### Consulta
de dados (SELECT): Escreva um comando SELECT para exibir todos os registros da tabela funcionários.

In [15]:
cursor.execute("select * from funcionarios;")
pd.DataFrame(cursor.fetchall(), columns=["id", "nome", "cargo", "salario", "data_contratacao"])

   id    nome                   cargo  salario data_contratacao
0   1  Felipe       Analista de Dados   5000.0       2022-01-15
1   2   Alice               Arquiteta   7700.0       2021-09-10
2   3    Acsa  Engenheira de Software   6000.0       2023-03-20
3   4   Aline      Cientista de Dados   8000.0       2022-11-05
4   5  Felipe       Analista de Dados   5000.0       2022-01-15
5   6   Alice               Arquiteta   7000.0       2021-09-10
6   7    Acsa  Engenheira de Software   6000.0       2023-03-20
7   8   Aline      Cientista de Dados   8000.0       2022-11-05
8   9   Bruno                 Gerente   9500.0       2020-05-18

### Filtro - WHERE:

- Selecione apenas os funcionários com salário superior a R$ 5000.
- Selecione os funcionários que trabalham como 'Gerente'.

In [16]:
cursor.execute("select * from funcionarios where salario > 5000;")
pd.DataFrame(cursor.fetchall(),columns=['id', 'nome', 'cargo', 'salario', 'data_contratacao'])

   id   nome                   cargo  salario data_contratacao
0   2  Alice               Arquiteta   7700.0       2021-09-10
1   3   Acsa  Engenheira de Software   6000.0       2023-03-20
2   4  Aline      Cientista de Dados   8000.0       2022-11-05
3   6  Alice               Arquiteta   7000.0       2021-09-10
4   7   Acsa  Engenheira de Software   6000.0       2023-03-20
5   8  Aline      Cientista de Dados   8000.0       2022-11-05
6   9  Bruno                 Gerente   9500.0       2020-05-18

In [17]:
cursor.execute("select * from funcionarios where cargo = 'Analista de Dados';")
pd.DataFrame(cursor.fetchall(), columns=['id', 'nome', 'cargo', 'salario', 'data_contratacao'])

   id    nome              cargo  salario data_contratacao
0   1  Felipe  Analista de Dados   5000.0       2022-01-15
1   5  Felipe  Analista de Dados   5000.0       2022-01-15

### Atualização de dados (UPDATE):

In [18]:
cursor.execute("update funcionarios set salario = salario * 1.1 where nome = 'Alice';")
conexao.commit()

### Exclusão de dados (DELETE):
 Exclui um dos funcionários que você inseriu.

In [19]:
cursor.execute("delete from funcionarios where nome = 'Felipe';")
conexao.commit()

### Contagem de registros:
 Conte o número total de funcionários na tabela.

In [20]:
cursor.execute("select count(*) from funcionarios;")
cursor.fetchall()

[(7,)]

# Parte 3: Agregação e Ordenação

---

### Funções de agregação ( SUM, AVG, MAX, MIN):
- Calcule a soma total dos salários.
- Calcule o salário médio da empresa.
- Encontre o salário mais alto e o mais baixo.

In [21]:
cursor.execute("""
    SELECT
        SUM(salario) AS soma_total_salarios,
        AVG(salario) AS salario_medio,
        MAX(salario) AS maior_salario,
        MIN(salario) AS menor_salario
    FROM funcionarios;
""")

resultado = cursor.fetchone()

pd.DataFrame([resultado], columns=[
    "Soma total dos salários",
    "Salário médio",
    "Maior salário",
    "Menor salário"
])

   Soma total dos salários  Salário médio  Maior salário  Menor salário
0                  53670.0    7667.142857         9500.0         6000.0