# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [1]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
#%pip install --upgrade selenium
#%pip install webdriver-manager

#### Passo 2: Importar bibliotecas

In [2]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [3]:
driver = webdriver.Chrome()

#### Passo 4: Acessar site

In [4]:
#url = 'https://pubmed.ncbi.nlm.nih.gov/'
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### Passo 5: Fechar navegador

In [5]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [6]:
driver = webdriver.Chrome()
#driver.get('https://www.zara.com/br/')
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### 6.2: Selecionar o campo de busca pelo id

In [7]:
campo_busca = driver.find_element(By.ID, "id_term")

#### 6.3: Escrever um texto no campo de busca

In [8]:
campo_busca.send_keys("Asma")

#### 6.4: Clicar no Botão Pesquisar

In [9]:
driver.find_element(By.CLASS_NAME, "search-btn").click()

#### 6.5: Fechar navegador

In [10]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [23]:
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/')
campo_busca = driver.find_element(By.ID, "id_term") 
campo_busca.send_keys("Pokemon", Keys.ENTER)

resultados = driver.find_elements(By.CLASS_NAME, "docsum-content")

print("Total de resultados encontrados:", len(resultados))

Total de resultados encontrados: 10

#### 7.1: Listar o título de todos os resultados

In [24]:
lista_de_titulos = []
for i in resultados:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, "docsum-title").text)

print(lista_de_titulos)

['Primary Care: Its Pokemon Moment.', 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.', 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.', 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.', 'Going Forward with Pokemon Go.', 'Pokemon contagion.', 'Random forests, sound symbolism and Pokemon evolution.', 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.', 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.', 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [25]:
lista_de_links = []
for j in resultados:
    lista_de_links.append(j.find_element(By.CLASS_NAME, "docsum-title").get_attribute("href"))
lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/38556037/',
 'https://pubmed.ncbi.nlm.nih.gov/31836333/',
 'https://pubmed.ncbi.nlm.nih.gov/33922978/',
 'https://pubmed.ncbi.nlm.nih.gov/37955949/',
 'https://pubmed.ncbi.nlm.nih.gov/30568365/',
 'https://pubmed.ncbi.nlm.nih.gov/11811868/',
 'https://pubmed.ncbi.nlm.nih.gov/36598905/',
 'https://pubmed.ncbi.nlm.nih.gov/27479151/',
 'https://pubmed.ncbi.nlm.nih.gov/39095579/',
 'https://pubmed.ncbi.nlm.nih.gov/29907559/']

#### 7.3: Acessar um dos links

In [14]:
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

In [15]:
url = lista_de_links[0]
print(url)
driver = webdriver.Chrome()
driver.get(f'{url}')

https://pubmed.ncbi.nlm.nih.gov/38556037/

##### 1) Título

In [31]:
titulo = driver.find_element(By.CLASS_NAME, "heading-title").text 
print(titulo)

Pokémon GO and Physical Activity in Asia: Multilevel Study

##### 2) Autores

In [19]:
autores = driver.find_element(By.CLASS_NAME, "inline-authors").text
print(autores)

Bryan Becker  1

##### 3) Ano de publicação

In [ ]:
ano_pub = driver.find_element(By.CLASS_NAME, "secondary-date").text
print(ano_pub)

Epub 2024 Mar 29.

##### 4) DOI

In [ ]:
doi = driver.find_element(By.CLASS_NAME, "id-link.usa-link--external").text
print(doi)

10.1016/j.amjmed.2024.03.020

##### 5) Tipo de publicação

In [ ]:
tipo_publicacao = driver.find_element(By.CLASS_NAME, "publication-type").text
print(tipo_publicacao)

Review

##### 6) Resumo

In [ ]:
resume = driver.find_element(By.CLASS_NAME, "abstract-content.selected").text
print(resume)

Primary care in the United States is undergoing bursts of evolution in response to health system stresses, changing demographics, and expansion of risk and value-based reimbursement structures. The impact of primary care remains substantive and associated with improved population health. However, the spectrum of services, the nature of the physicians involved and new ways of including the patient in her, or his own care suggests that a new definition of primary care be considered, and patient expectations be heeded and understood. Evolutionary bursts yield new traits and in primary care, they are spawning new care models with significant implications for general internal medicine, internal medicine/pediatrics trained individuals and medicine subspecialties given the focus of these models on Medicare Advantage. Ultimately, changes in reimbursement and creative incentives will be two factors among many that will solidify the next stage of primary care in the United States.

##### 7) Link de acesso (como registro de referência)

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [28]:
colunas = ['Titulo', 'Autores', 'Ano_Publicacao', 'DOI', 'Tipo_Publicacao', 'Resumo', "link_acesso"]
tabela = pd.DataFrame(columns=colunas)

tabela.head()

Empty DataFrame
Columns: [Titulo, Autores, Ano_Publicacao, DOI, Tipo_Publicacao, Resumo, link_acesso]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [ ]:
import time

driver = webdriver.Chrome()


for i in lista_de_links:
    driver.get(i)
    time.sleep(2)
    try:
        titulo = driver.find_element(By.CLASS_NAME, "heading-title").text 
    except:
        titulo = None
    try:
        autores = driver.find_element(By.CLASS_NAME, "inline-authors").text
    except:
        autores = None
    try:
        ano_pub = driver.find_element(By.CLASS_NAME, "secondary-date").text
    except:
        ano_pub = None
    try:
        doi = driver.find_element(By.CLASS_NAME, "id-link.usa-link--external").text
    except:
        doi = None
    try:
        tipo_publicacao = driver.find_element(By.CLASS_NAME, "publication-type").text
    except:
        tipo_publicacao = None
    try:
        resume = driver.find_element(By.CLASS_NAME, "abstract-content.selected").text
    except:
        resume = None

    tabela = pd.concat([tabela, pd.DataFrame([[titulo, autores, ano_pub, doi, tipo_publicacao, resume, i]], columns=colunas)], ignore_index=True)

#### 3) Visualizar tabela

In [36]:
tabela.head(10)

,Titulo,Autores,Ano_Publicacao,DOI,Tipo_Publicacao,Resumo,link_acesso
0,None,Bryan Becker 1,Epub 2024 Mar 29.,10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...,https://pubmed.ncbi.nlm.nih.gov/38556037/
1,Impact of Pokémon Go on Physical Activity: A S...,"Madina Khamzina 1 , Kaustubh V Parab 2 , Ruo...",Epub 2019 Dec 10.,10.1016/j.amepre.2019.09.005,Meta-Analysis,Context: Pokémon Go is a popular mobile augmen...,https://pubmed.ncbi.nlm.nih.gov/31836333/
2,Effects of Pokémon GO on Physical Activity and...,"Jung Eun Lee 1 , Nan Zeng 2 , Yoonsin Oh 3 ...",None,10.3390/jcm10091860,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://pubmed.ncbi.nlm.nih.gov/33922978/
3,Influence of Pokémon GO on Physical Activity a...,"Haiyan Liang 1 , Xi Wang 2 , Ruopeng An 2",None,10.2196/49019,Review.,"Background: Pokémon GO, an augmented reality g...",https://pubmed.ncbi.nlm.nih.gov/37955949/
4,Going Forward with Pokemon Go,"Yvette Chong 1 , Dean Krishen Sethi 1 , Char...",None,10.4103/JETS.JETS_87_17,Review,Pokemon Go is an augmented reality (AR) game w...,https://pubmed.ncbi.nlm.nih.gov/30568365/
5,Pokemon contagion,"B G Zifkin, D G Kasteleijn-Nolst Trenité",None,10.1097/00007611-200112000-00025,Comment,None,https://pubmed.ncbi.nlm.nih.gov/11811868/
6,"Random forests, sound symbolism and Pokémon ev...","Alexander James Kilpatrick 1 , Aleksandra Ćwi...",eCollection 2023.,10.1371/journal.pone.0279350,Review.,This study constructs machine learning algorit...,https://pubmed.ncbi.nlm.nih.gov/36598905/
7,Pokémon Go and augmented virtual reality games...,"Maeve Serino 1 , Kyla Cordrey, Laura McLaughl...",None,10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://pubmed.ncbi.nlm.nih.gov/27479151/
8,Pokemon inhibits Bim transcription to promote ...,"Yan Wang # 1 2 , Huiling Zeng # 1 , Li Li ...",None,10.1007/s00432-024-05904-1,None,Purpose: This study aims to determine whether ...,https://pubmed.ncbi.nlm.nih.gov/39095579/
9,Pokémon GO and Physical Activity in Asia: Mult...,"Ben D Ma 1 2 , Sai Leung Ng 1 , Tim Schwan...",None,10.2196/jmir.9670,Review.,Background: Physical activity has long been co...,https://pubmed.ncbi.nlm.nih.gov/29907559/

#### 4) Exportar DataFrame para Excel

In [ ]:
#%pip install openpyxl

In [38]:
exportar_excel = tabela.to_excel("tabela_pubmed.xlsx", index=False)